name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-binary:
    name: Release binary on Linux and Macos
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-latest]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Binary
        run: make release-binary

      - name: Release Binary
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# TODO: update release docker
#  release-docker:
#    name: Release docker-images of bitxhub and bitxhub-solo
#    runs-on: ${{matrix.os}}
#    strategy:
#      matrix:
#        os: [ubuntu-latest]
#        go_version: [1.15]
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{ matrix.go_version }}
#
#      - name: Check out code
#        uses: actions/checkout@v3
#
#      - name: Build Binary
#        run: make release-binary
#
#      - name: Build and push bitxhub image with raft consensus
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: meshplus/bitxhub
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          dockerfile: Dockerfile-raft
#          tag_names: true
#
#      - name: Build and push bitxhub image with solo consensus
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: meshplus/bitxhub-solo
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          dockerfile: Dockerfile-solo
#          tag_names: true