name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-binary:
    name: Release binary on Linux and Macos
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-latest]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build Binary
        run: make release-binary

      - name: Release Binary
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docker:
    name: Release docker-images of bitxhub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build and push bitxhub image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: meshplus/bitxhub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_names: true